version: "3"

services:
  backend:
    build: ./fake_olx_springboot/.
    ports:
      - 8081:8081
    
  frontend:
    build: ./fake-olx-app/.
    ports:
      - 8080:8080
    depends_on: 
      - backend

